# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Cache data for use in ogwrangler
#' @export
CreateCache <- function() {
    invisible(.Call('_ogwrangler_CreateCache', PACKAGE = 'ogwrangler'))
}

#' Get code from geo for each postcode
#' @export
ogpost <- function(postcode, geo) {
    .Call('_ogwrangler_ogpost', PACKAGE = 'ogwrangler', postcode, geo)
}

#' Find text in names of geographies
#' @export
ogfind <- function(text) {
    .Call('_ogwrangler_ogfind', PACKAGE = 'ogwrangler', text)
}

#' Find named entities in geography geo
#' @export
ogcode <- function(name, geo) {
    .Call('_ogwrangler_ogcode', PACKAGE = 'ogwrangler', name, geo)
}

#' Get property of a code
#' @export
ogwhat <- function(code, property = "name") {
    .Call('_ogwrangler_ogwhat', PACKAGE = 'ogwrangler', code, property)
}

